#!/bin/bash
map="Frums - Pictured as Perfect and Plus (K 3 V R A L) [[]!) []= \`\$[-_=  !'' -$...].osu";
dist=4;
lc=$(($(sed -n -e '/\[HitObjects\]/,$p' "$map" | tail -n +2 | wc -l) - 1));

#w_spin_t=(251076 251392 251707 251813 252023 252076 252128 252181);
w_spin_t=(300000);
w_spin="";
for i in ${w_spin_t[@]}; do
	w_spin="$w_spin -w $i:1";
done

seq_part=2;
for k in $(seq 0 $seq_part); do
	if [ "$k" -eq "0" ]; then
		# Part 1	
		bnpd_l="";
		bnpd_r="";
		t_length="26.31";
		bs=(176 328 112 280 64 244 32 220 16 208 8 202 0 196 8 202 16 208 32 220 64 244 112 280);
		bs_len=${#bs[@]};
		start_time=252339;
		dir=512;
		switch=1;
		seq_end=238;
		for i in $(seq 0 2 $seq_end); do
			temp_mod=$(($i % $bs_len));
			if [ "$temp_mod" -eq "0" ]; then
				dir=$((512 - $dir));
				switch=$((1 - $switch));
			fi
			
			x_left=$(echo $(($dir - ${bs[($i + $switch) % $bs_len]})) | sed "s/-//");
			x_right=$(echo $(($dir - ${bs[($i + (1 - $switch)) % $bs_len]})) | sed "s/-//");
			time=$(echo "scale=0; ($(echo "($t_length * ($i / 2)) + $start_time" | bc) - 0.5) / 1" | bc);

			echo "$k/$seq_part | $i | $time | $x_left , $x_right";

			bnpd_l="$bnpd_l|$x_left:$time";
			bnpd_r="$x_right:$time|$bnpd_r";
		done

		bnpd_l=$(echo "$bnpd_l" | tail -c +2);
		bnpd_r=$(echo "$bnpd_r" | head -c -2);

		lc_new=$(wc -l < "$map");

		bnprdctr -b "$map" -o /tmp/file.osu -s "$bnpd_l|$bnpd_r" $w_spin -d "$dist" \
		&& cat /tmp/file.osu >> "$map";

		lc=$(($(wc -l < "$map") - $lc_new + $lc));
	elif [ "$k" -eq "1" ]; then
		# Part 2
		bs=(96 416);
		bs_len=${#bs[@]};
		start_time=255497;
		gap_length=158;
		end_length=131;
		for i in $(seq 0 3); do
			x_left=${bs[$i % $bs_len]};
			x_right=$(($x_left + ((($i % 2 == 0) - ($i % 2 != 0)) * 128)));
			time_s=$((($gap_length * $i) + $start_time));
			time_e=$(($end_length + $time_s));

			echo "$k/$seq_part | $i | $time_s , $time_e | $x_left , $x_right";

			lc_new=$(wc -l < "$map");

			bnprdctr -b "$map" -o /tmp/file.osu -s "$x_left:$time_s|$x_right:$time_s|$x_right:$time_e|$x_left:$time_e" $w_spin -d "$dist" -u "$lc" \
			&& cat /tmp/file.osu >> "$map";

			lc=$(($(wc -l < "$map") - $lc_new + $lc));
		done
	elif [ "$k" -eq "2" ]; then
		# Part 3
		start_time=256128;
		gap_length=158;
		end_length=79;
		dir=512;
		for i in $(seq 0 3); do
			dir=$((512 - $dir));
			x1_left=$(echo $(($dir - 0)) | sed "s/-//");
			x2_left=$(echo $(($dir - 128)) | sed "s/-//");
			x1_right=$(echo $(($x1_left - ((($i % 2 != 0) - ($i % 2 == 0)) * 256))) | sed "s/-//");
			x2_right=$(echo $(($x2_left - ((($i % 2 != 0) - ($i % 2 == 0)) * 256))) | sed "s/-//");
			time_s=$((($gap_length * $i) + $start_time));
			if [ "$i" -ne "3" ]; then
				time_e=$(($end_length + $time_s));
			else
				time_e=$(($gap_length + $time_s));
			fi

			echo "$k/$seq_part | $i | $time_s , $time_e | $x1_left , $x2_left ; $x1_right , $x2_right";

			lc_new=$(wc -l < "$map");

			bnprdctr -b "$map" -o /tmp/file.osu -s "$x1_left:$time_s|$x1_right:$time_s|$x2_right:$time_e|$x2_left:$time_e" $w_spin -d "$dist" -u "$lc" \
			&& cat /tmp/file.osu >> "$map";

			lc=$(($(wc -l < "$map") - $lc_new + $lc));
		done
	fi
done
