#!/bin/bash
source "./functions.sh"

map="Frums - Pictured as Perfect and Plus (K 3 V R A L) [[]!) []= \`\$[-_=  !'' -$...].osu";
dist=4;
t_length="26.31";

bnpd_l="";
bnpd_r="";

#w_spin_t=(251076 251392 251707 251813 252023 252076 252128 252181);
w_spin_t=(300000);
w_spin="";
for x in ${w_spin_t[@]}; do
	w_spin="-w $x:1 $w_spin";
done

seq_part=2;
for k in $(seq 0 $seq_part); do
	if [ "$k" -eq "0" ]; then
		# Part 1
		# TODO Reverse traversal when hitting the end of array
		bs=(176 328 112 280 64 244 32 220 16 208 8 202 0 196 8 202 16 208 32 220 64 244 112 280);
		bs_len=${#bs[@]};
		start_time=252339;
		dir=512;
		switch=1;
		seq_end=238;
		for i in $(seq 0 2 $seq_end); do
			# TODO some errors
			temp_mod=$(fbc "$i % $bs_len");
			if [ "$temp_mod" -eq "0" ]; then
				dir=$(fbc "512 - $dir");
				switch=$(fbc "1 - $switch");
			fi
			
			x_left=$(fabs $(fbc "$dir - ${bs[$(fbc "($i + $switch) % $bs_len")]}"));
			x_right=$(fabs $(fbc "$dir - ${bs[$(fbc "($i + (1 - $switch)) % $bs_len")]}"));
			time=$(fpf $(fbc "($t_length * ($i / 2)) + $start_time"));

			echo "$k/$seq_part | $i | $time | $x_left , $x_right";

			bnpd_l="$bnpd_l|$x_left:$time";
			bnpd_r="$x_right:$time|$bnpd_r";
		done
	elif [ "$k" -eq "1" ]; then
		# Part 2
		bs=(184 104 24 104);
		bs_len=${#bs[@]};
		bs_i=0;
		for j in $(seq 0 1); do
			start_time=$(fbc "255497 + ($j * 316)");
			seq_end=11;
			for i in $(seq 0 $seq_end); do
				temp_bs=$(fbc "$i % ($bs_len - 1)");
				if [ "$temp_bs" -eq "0" ]; then
					old=${bs[$(fbc "$bs_i % $bs_len")]};
					curr=${bs[$(fbc "($bs_i + 1) % $bs_len")]};
					bs_i=$(fbc "$bs_i + 1");
				fi

				time=$(fpf $(fbc "($t_length * $i) + $start_time"));
				if [ "$i" -ge "3" ] && [ "$i" -le "7" ]; then
					if [ "$i" -eq "3" ] || [ "$i" -eq "7" ]; then
						old_empty=256;
					else
						old_empty=184;
					fi

					x_left=$old;
					x_lmid=$old_empty;
					x_right=$(fbc "512 - $x_left")
					x_rmid=$(fbc "512 - $x_lmid");

					# TODO middle empty
					bnpd_l="$bnpd_l|$x_left:$time|$x_lmid:$time";
					bnpd_r="$x_rmid:$time|$x_right:$time|$bnpd_r";
				else
					x_left=$old;
					x_right=$(fbc "512 - $x_left")

					bnpd_l="$bnpd_l|$x_left:$time";
					bnpd_r="$x_right:$time|$bnpd_r";
				fi

				echo "$k/$seq_part | $j | $i | $time";

				old=$curr;
			done
		done
	elif [ "$k" -eq "2" ]; then
		# Part 3
		start_time=256128;
		seq_end=24;
		direction=-32;
		bs_i=192;
		for i in $(seq 0 $seq_end); do
			x_left=$(fbc "$bs_i");
			x_right=$(fbc "$x_left + 128");
			time=$(fpf $(fbc "($t_length * $i) + $start_time"));

			bnpd_l="$bnpd_l|$x_left:$time";
			bnpd_r="$x_right:$time|$bnpd_r";

			temp_dir=$(fbc "$bs_i + $direction");
			if [ "$temp_dir" -lt "0" ] || [ "$temp_dir" -gt "448" ]; then
				direction=$(fbc "-1 * $direction");
			fi
			bs_i=$(fbc "$bs_i + $direction");

			echo "$k/$seq_part | $i | $x_left , $x_right | $time";
		done
	fi
done

bnpd_l=$(echo "$bnpd_l" | tail -c +2);
bnpd_r=$(echo "$bnpd_r" | head -c -2);

bnprdctr -b "$map" -o /tmp/file.osu -s "$bnpd_l|$bnpd_r" $w_spin -d "$dist" \
&& cat /tmp/file.osu >> "$map";
