#!/bin/bash
map="Frums - Pictured as Perfect and Plus (K 3 V R A L) [[]!) []= \`\$[-_=  !'' -$...].osu";
dist=4;
lc=$(($(sed -n -e '/\[HitObjects\]/,$p' "$map" | tail -n +2 | wc -l) - 1));
if [ "$lc" -lt "0" ]; then
	lc=0;
fi

#w_spin_t=(256865 256997 257128 257260);
w_spin_t=(300000);
w_spin="";
for i in ${w_spin_t[@]}; do
	w_spin="$w_spin -w $i:1";
done

seq_part=3;
for k in $(seq 0 $seq_part); do
	if [ "$k" -eq "0" ]; then
		# Part 1
		bs=(257392 257707 257865);
		bs_len=${#bs[@]};

		for i in $(seq 0 $(($bs_len - 1))); do
			x_left=$(($i * 224));
			x_right=$(($x_left + 64));
			time_s=${bs[$i]};
			time_e=$(($time_s + 26));

			echo "$k/$seq_part | $i | $time_s , $time_e | $x_left , $x_right";

			lc_new=$(wc -l < "$map");

			bnprdctr -b "$map" -o /tmp/file.osu -s "$x_left:$time_s|$x_right:$time_s|$x_right:$time_e|$x_left:$time_e" $w_spin -d "$dist" -u "$lc" \
			&& cat /tmp/file.osu >> "$map";

			lc=$(($(wc -l < "$map") - $lc_new + $lc));
		done
	elif [ "$k" -eq "1" ]; then
		# Part 2
		bs=(257971 258207 258392 258497 258602 258681);
		bs_len=${#bs[@]};
		curr=0;

		for i in $(seq 0 $(($bs_len - 1))); do
			x_left=$(echo $(((512 * ($i % 2 != 0)) - 416 + ($curr * 32))) | sed "s/-//");
			x_right=$(($x_left + ((($i % 2 != 0) - ($i % 2 == 0)) * 64)));
			time_s=${bs[$i]};
			time_e=$(($time_s + 26));
			curr=$(($curr + (($i + 1) % 2 == 0)));

			echo "$k/$seq_part | $i | $time_s , $time_e | $x_left , $x_right";

			lc_new=$(wc -l < "$map");

			bnprdctr -b "$map" -o /tmp/file.osu -s "$x_left:$time_s|$x_right:$time_s|$x_right:$time_e|$x_left:$time_e" $w_spin -d "$dist" -u "$lc" \
			&& cat /tmp/file.osu >> "$map";

			lc=$(($(wc -l < "$map") - $lc_new + $lc));
		done
	elif [ "$k" -eq "2" ]; then
		# Part 3
		bs=(258813 259997 260234 260602);
		bs_len=${#bs[@]};
		bnpd="";

		for j in $(seq 0 1); do
			bnpd_l="";
			bnpd_r="";
			
			for i in $(seq 0 $(($bs_len - 1))); do
				x_left=$(echo $(((512 * $j) - (192 + (160 * (($i == 2) - ($i == 1)))))) | sed "s/-//");
				x_right=$(($x_left + (128 * (($j == 0) - ($j != 0)))));
				time=${bs[$i]};

				echo "$k/$seq_part | $i | $time | $x_left , $x_right";

				bnpd_l="$bnpd_l|$x_left:$time";
				bnpd_r="$x_right:$time|$bnpd_r";
			done

			bnpd_l=$(echo "$bnpd_l" | tail -c +2);
			bnpd_r=$(echo "$bnpd_r" | head -c -2);
			bnpd="$bnpd -s $bnpd_l|$bnpd_r"
		done

		lc_new=$(wc -l < "$map");

		bnprdctr -b "$map" -o /tmp/file.osu $bnpd $w_spin -d "$dist" -u "$lc" \
		&& cat /tmp/file.osu >> "$map";

		lc=$(($(wc -l < "$map") - $lc_new + $lc));
	elif [ "$k" -eq "3" ]; then
		# Part 4
		bs=(260865 261207 261339 261576 261707 261813);
		bs_len=${#bs[@]};

		for i in $(seq 0 2 $(($bs_len - 1))); do
			x_left=$(((160 * ($i / 2)) + (32 * ($i == $bs_len))));
			x_right=$(((160 * (($i / 2) + 1)) + (32 * ($i == $bs_len))));
			time_s=${bs[$i]};
			time_e=${bs[$i + 1]};

			echo "$k/$seq_part | $i | $time_s , $time_e | $x_left , $x_right";

			lc_new=$(wc -l < "$map");

			bnprdctr -b "$map" -o /tmp/file.osu -s "$x_left:$time_s|$x_right:$time_s|$x_right:$time_e|$x_left:$time_e" $w_spin -d "$dist" -u "$lc" \
			&& cat /tmp/file.osu >> "$map";

			lc=$(($(wc -l < "$map") - $lc_new + $lc));
		done
	fi
done
